name: Simple CI/CD for Middle Exam Cloud Computing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa_git
          chmod 600 ~/.ssh/id_rsa_git

      - name: Make sure target directory exists
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_git ec2-user@${{ secrets.EC2_HOST }} "mkdir -p /usr/share/nginx/html/blog"

      - name: Copy files to EC2
        run: |
          echo "Deploying to EC2 server..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_git -r * ec2-user@${{ secrets.EC2_HOST }}:/usr/share/nginx/html/blog
